config {
    type: "incremental",
    uniqueKey: ["trip_key"],
    assertions: {
        uniqueKey: ["trip_key"]
    },
    bigquery: {
        partitionBy: "date_trunc(trip_date,month)",
        clusterBy: ["trip_date", "taxi_id"]
    }

}

WITH
  src AS (
  SELECT

    unique_key AS trip_key,
    taxi_id,
    DATETIME(trip_start_timestamp) AS trip_start_dt,
    DATE(DATETIME(trip_start_timestamp)) AS trip_date,
    COALESCE(DATETIME(trip_end_timestamp), DATETIME(TIMESTAMP_ADD(trip_start_timestamp, INTERVAL COALESCE(trip_seconds,0) second))) AS trip_end_dt,
    COALESCE(trip_seconds,0) AS trip_seconds,
    ROUND(COALESCE(trip_seconds,0)/60,2) AS trip_minutes,
    payment_type,
    COALESCE(fare,0) AS fare,
    COALESCE(tips,0) AS tips,
    COALESCE(trip_total,0) AS trip_total
  FROM
    ${ref("taxi_trips")}
  WHERE
    trip_start_timestamp >= checkpoint ),
  dedupe AS(
  SELECT
    *,
    ROW_NUMBER() OVER (PARTITION BY trip_key ORDER BY trip_start_dt) AS rn
  FROM
    src)
SELECT
  
  cast(format_date('%Y%m%d', trip_date) as int64) as date_key,
  
  * EXCEPT (rn)
FROM
  dedupe
WHERE
  rn = 1

pre_operations {
  DECLARE
    checkpoint DEFAULT (
    ${
        when(incremental(),
            `select timestamp_sub(timestamp(max(trip_start_dt)), interval 7 day) from ${self()}`,
            `select timestamp("2013-01-01")`)
    }
    )
}
