config {
    type: "table",
    assertions: { 
        uniqueKey: ["trip_key"]
    },
    bigquery:{
        partitionBy: "date_trunc(trip_date,month)",
        clusterBy: ["trip_date","taxi_id"]
    }

}


with src as (

SELECT
unique_key as trip_key
,taxi_id
,datetime(trip_start_timestamp) as trip_start_dt
,date(datetime(trip_start_timestamp)) as trip_date

,coalesce(datetime(trip_end_timestamp),
datetime(timestamp_add(trip_start_timestamp, interval coalesce(trip_seconds,0) second))) as trip_end_dt
,coalesce(trip_seconds,0) as trip_seconds

,round(coalesce(trip_seconds,0)/60,2) as trip_minutes
,payment_type
,coalesce(fare,0) as fare
,coalesce(tips,0) as tips
,coalesce(trip_total,0) as trip_total





from ${ref("taxi_trips")}

), dedupe as(

select
*
,row_number() over (partition by trip_key order by trip_start_dt) as rn
from src)


select * except (rn) from dedupe where rn = 1
