config {
    type: "table"
}
with calculate as(
select

taxi_id
,count(*) as electronics_trips
,safe_divide(sum(tips),count(*)) as tips_per_trip
,safe_divide(sum(tips),sum(fare)) as tip_rate
,sum(tips) as total_tips

from ${ref("stg_trips")}
where
trip_date >= date_sub((select max(trip_date) from ${ref("stg_trips")}), interval 3 month)
and 
payment_type in ('Credit Card', 'Mobile') -- other payment method ignored due to data collection gap

group by taxi_id
order by total_tips desc
)

select * from calculate
limit 100


