config {
    type: "table"
}

select

taxi_id
,count(*) as electronics_trips
,safe_divide(sum(tips),count(*)) as tips_per_trip
,safe_divide(sum(tips),sum(fare)) as tip_rate
,sum(tips) as total_tips

from ${ref("stg_trips")}
where
trip_date >= date_sub((select max(trip_date) from ${ref("stg_trips")}), interval 3 month)
and 
payment_type in ('Credit Card', 'Mobile', 'Prcard', 'Pcard', 'Way2ride')

group by taxi_id
order by total_tips desc
limit 100


