config {
    type: "table",
    assertions: {
        uniqueKey: ["date_day"]
    }

}

with calendar as (
select date_day
from  unnest (
generate_date_array(
    (select min(trip_date) from ${ref("stg_trips")}),
    (select max(trip_date) from ${ref("stf_trips")}), 
    interval 1 day
) as date_day)

)

select

a.date_day
,extract(year from a.date_day) as year
,extract(month from a.date_day) as month
,format_date('%Y-%m', a.date_day) as year_month
,format_date('%A', a.date_day) as day_of_week
,formate_date('%B',a.date_day) as month_name




from calendar a
left join ${ref("dim_us_holiday")} b on a.date_day = b.holiday_date

